import Head from "next/head";

interface HomeProps {
  prefix: string;
}

export default function Home({ prefix }: HomeProps) {
  return (
    <>
      <Head>
        <title>PDF editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={`${prefix}/favicon.ico`} />
      </Head>
      <main className="text-3xl font-bold underline">Hello world</main>
    </>
  );
}
